/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java2024;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author Lim Ee Chian
 */
public class HomePage extends javax.swing.JFrame {
    
    public HomePage() {
        initComponents();
        
        customizeButtons();
        UserUtilityClass.displayUsername(tfUsername);
    }
    
    private void customizeButtons() {
    
        switch (AuthenticationClass.getCurrentUserSession().getUserRole()) {
            case "OFFICER" -> {
                btnOnlyOfficer.setVisible(true);
                btnOnlySalesperson.setVisible(false);
                btnOnlyAdministrator.setVisible(false);
                
                
                // for testing - go to QuotationsListPage
                btnViewQuotationsList.setVisible(true);
                // for testing - go to SaleOrdersListPage
                btnViewSaleOrdersList.setVisible(true);
            }
            case "SALESPERSON" -> {
                btnOnlyOfficer.setVisible(false);
                btnOnlySalesperson.setVisible(true);
                btnOnlyAdministrator.setVisible(false);
                
                
                // for testing - go to QuotationsListPage
                btnViewQuotationsList.setVisible(true);
                // for testing - go to SaleOrdersListPage
                btnViewSaleOrdersList.setVisible(true);
            }
            case "ADMIN" -> {
                btnOnlyOfficer.setVisible(false);
                btnOnlySalesperson.setVisible(false);
                btnOnlyAdministrator.setVisible(true);
                
                
                // for testing - go to QuotationsListPage
                btnViewQuotationsList.setVisible(true);
                // for testing - go to SaleOrdersListPage
                btnViewSaleOrdersList.setVisible(true);
            }
            default -> {
            }
        }
//        if (userRole.equals("Officer")) {
//            btnOnlyOfficer.setVisible(true);
//            btnOnlySalesperson.setVisible(false);
//            btnOnlyAdministrator.setVisible(false);
//        } else if (userRole.equals("Salesperson")) {
//            btnOnlyOfficer.setVisible(false);
//            btnOnlySalesperson.setVisible(true);
//            btnOnlyAdministrator.setVisible(false);
//        } else if (userRole.equals("Administrator")) {
//            btnOnlyOfficer.setVisible(false);
//            btnOnlySalesperson.setVisible(false);
//            btnOnlyAdministrator.setVisible(true);
//        }
            }
    
/*    private void displayUsername() {
        // Get the current user's session information
        UserSessionClass currentUserSession = AuthenticationClass.getCurrentUserSession();
        
        // Check if a user is logged in
        if (currentUserSession != null) {
            // Get the username and display the tfUsername field
            String currentUserID = currentUserSession.getUserID();
            String currentUsername = getUsernameFromUserID(currentUserID);
            
            if (currentUsername != null) {
                // Display the tfUsername field
                tfUsername.setText(currentUsername);
            }
        }
    }
    
    private String getUsernameFromUserID(String userID) {
        try (FileReader fr = new FileReader("UsersTable.txt");
            BufferedReader br = new BufferedReader(fr)) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] col = line.split(";");
                String userIDFromFile = col[0].trim();
                String usernameFromFile = col[3].trim();
                
                
                // Check if the input userID matches with any user in the file
                if (userID.equals(userIDFromFile)) {
                    return usernameFromFile;
                }
            }
        } catch (IOException e) {
            System.out.println("IOException occured when get username from userID through UsersTable.txt: " + e.getMessage());
        }
        
        return null; // Return null if userID is not found
    } */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOnlyOfficer = new javax.swing.JButton();
        btnOnlySalesperson = new javax.swing.JButton();
        btnOnlyAdministrator = new javax.swing.JButton();
        tfUsername = new javax.swing.JTextField();
        btnViewQuotationsList = new javax.swing.JButton();
        btnViewSaleOrdersList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOnlyOfficer.setText("only officer have access");
        btnOnlyOfficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnlyOfficerActionPerformed(evt);
            }
        });

        btnOnlySalesperson.setText("only salesperson");

        btnOnlyAdministrator.setText("only admin");

        btnViewQuotationsList.setText("View Quotations List");
        btnViewQuotationsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewQuotationsListActionPerformed(evt);
            }
        });

        btnViewSaleOrdersList.setText("View Sale Orders List");
        btnViewSaleOrdersList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSaleOrdersListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewQuotationsList, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(btnViewSaleOrdersList, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOnlyOfficer, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(btnOnlySalesperson, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnOnlyAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOnlyOfficer, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOnlySalesperson, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOnlyAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewQuotationsList)
                    .addComponent(btnViewSaleOrdersList))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOnlyOfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnlyOfficerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOnlyOfficerActionPerformed

    private void btnViewQuotationsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewQuotationsListActionPerformed
        // Create an instance of QuotationsListPage
        QuotationsListPage quotationsListPage = new QuotationsListPage();
        
        // Set its visibilty to true (to show the QuotationsListPage)
        quotationsListPage.setVisible(true);
        
        // Hide the current page (HomePage)
        // this.setVisible(false);
    }//GEN-LAST:event_btnViewQuotationsListActionPerformed

    private void btnViewSaleOrdersListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSaleOrdersListActionPerformed
        // Create an instance of SaleOrdersListPage
        SaleOrdersListPage saleOrdersListPage = new SaleOrdersListPage();
        
        // Set its visibility to true (to show the SaleOrdersListPage)
        saleOrdersListPage.setVisible(true);
        
        
    }//GEN-LAST:event_btnViewSaleOrdersListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOnlyAdministrator;
    private javax.swing.JButton btnOnlyOfficer;
    private javax.swing.JButton btnOnlySalesperson;
    private javax.swing.JButton btnViewQuotationsList;
    private javax.swing.JButton btnViewSaleOrdersList;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
